---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-run-creator
  namespace: pipeline-service-metrics
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelines
      - tasks
    verbs:
      - "*"
