apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.32.0/release.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/securityContext
        value: {}
    target:
      kind: Deployment
      name: tekton-pipelines-controller
      namespace: tekton-pipelines
  - patch: |-
      - op: replace
        path: /spec/template/spec/securityContext
        value: {}
    target:
      kind: Deployment
      name: tekton-pipelines-webhook
      namespace: tekton-pipelines