apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value: {}
    target:
      kind: Deployment
      name: tekton-pipelines-controller
      namespace: tekton-pipelines
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value: {}
    target:
      kind: Deployment
      name: tekton-pipelines-webhook
      namespace: tekton-pipelines