---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-admin
rules:
  - apiGroups:
      - ""
    resources:
      - "events"
      - "limitranges"
      - "resourcequotas"
      - "secrets"
      - "serviceaccounts"
      - "persistentvolumes"
      - "persistentvolumeclaims"
      - "endpoints"
      - "replicationcontrollers"
      - "podtemplates"
      - "nodes"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "namespaces"
      - "pods"
      - "services"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "replicasets"
      - "daemonsets"
      - "statefulsets"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "apiresource.kcp.dev"
    resources:
      - "apiresourceimports"
      - "negotiatedapiresources"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apis.kcp.dev"
    resources:
      - "apibindings"
      - "apiexports"
      - "apiresourceschemas"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "certificates.k8s.io"
    resources:
      - "certificatesigningrequests"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "flowcontrol.apiserver.k8s.io"
    resources:
      - "flowschemas"
      - "prioritylevelconfigurations"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "clusterroles"
      - "clusterrolebindings"
      - "roles"
      - "rolebindings"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "tekton.dev"
    resources:
      - "conditions"
      - "pipelineresources"
      - "runs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "triggers.tekton.dev"
    resources:
      - "clustertriggerbindings"
      - "eventlisteners"
      - "triggers"
      - "triggerbindings"
      - "triggertemplates"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "triggers.tekton.dev"
    resources:
      - "clusterinterceptors"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - "workload.kcp.dev"
    resources:
      - "workloadclusters"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "mutatingwebhookconfigurations"
      - "validatingwebhookconfigurations"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "machine.openshift.io"
    resources:
      - "machinehealthchecks"
      - "machinesets"
      - "machines"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apiregistration.k8s.io"
    resources:
      - "apiservices"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "networkpolicies"
      - "ingresses"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apps"
    resources:
      - "controllerrevisions"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "operator.openshift.io"
    resources:
      - "etcds"
      - "networks"
      - "kubecontrollermanagers"
      - "openshiftapiservers"
      - "consoles"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - "volumeattachments"
      - "csistoragecapacities"
      - "csinodes"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "user.openshift.io"
    resources:
      - "users"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "build.openshift.io"
    resources:
      - "builds"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "oauth.openshift.io"
    resources:
      - "oauthauthorizetokens"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "template.openshift.io"
    resources:
      - "templates"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "node.k8s.io"
    resources:
      - "runtimeclasses"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apiserver.openshift.io"
    resources:
      - "apirequestcounts"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "scheduling.k8s.io"
    resources:
      - "priorityclasses"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "batch"
    resources:
      - "cronjobs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apps.openshift.io"
    resources:
      - "deploymentconfigs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "autoscaling"
    resources:
      - "horizontalpodautoscalers"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "argocd-manager-crd-admin-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-admin
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: kube-system