apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: registration-pipeline
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
spec:
  params:
    - name: repo_url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
        params:
          - name: depth
            value: "500"
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: argocd-register
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: register-to-argo
              image: quay.io/fgiloux/pipelines-argocd:latest
              workingDir: $(workspaces.source.path)
              env:
                - name: ARGO_URL
                  valueFrom:
                    secretKeyRef:
                      name: "argocd-credentials"
                      key: "url"
                - name: ARGO_USER
                  valueFrom:
                    secretKeyRef:
                      name: "argocd-credentials"
                      key: "user"
                - name: ARGO_PWD
                  valueFrom:
                    secretKeyRef:
                      name: "argocd-credentials"
                      key: "pwd"
                - name: DATA_DIR
                  value: $(workspaces.source.path)
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Mi
