apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - openshift-argocd-svc.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/securityContext
        value: {}
    target:
      kind: Deployment
      name: argocd-redis
      namespace: argocd