---
name: Upgrade kcp
on:
  push:
    branches:
      - auto_upgrade_kcp
      #  schedule:
#    - cron: "0 0 * * *"
#  workflow_dispatch:

jobs:
  kcp-upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          ref: auto_upgrade_kcp

#      - name: Checkout branch for creating a PR
#        uses: actions/checkou@v3
#        with:
#          ref: upgrade_kcp

      - name: Check if a new kcp version exists and update the files if it does
        run: |
          ./images/kcp-upgrade/upgrade.sh

      - name: Create PR
        id: create-pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.UPGRADE_TOKEN }}
          commit-message: Upgrade kcp to the latest available version
          branch: upgrade_kcp
          delete-branch: true
          title: 'Upgrade kcp to the latest available version'

